### ISSUE TITLE
specify font size explicitly

### ISSUE THREAD

**Issue by CodeOptimist** [zzzz465/ModMisMatchFormatter#2]
Not a fault of your mod, but other (badly behaved) mods can change font size and not reset it, and then you get: 

![image](https://user-images.githubusercontent.com/52485/66280783-87e10700-e875-11e9-9451-6d7721a95880.png)

```
var font = Text.Font;
Text.Font = GameFont.Small;
...
Text.Font = font;
```

**Comment by zzzz465** [comment]
it will be fixed in version 1.1.0, font size is 15 for now.
